name: Test, build and push to github packages
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - '*'
    tags:
      - '*.*.*'

jobs:
  build-images:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV for branch master/main
        if: ${{ github.ref == 'refs/heads/master' }}
        run: echo "RELEASE_VERSION=latest" >> $GITHUB_ENV
      - name: Set ENV for tags
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set ENV for specific branch
        if: ${{ startsWith(github.ref, 'refs/heads/') && !endsWith(github.ref, '/master') }}
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}-${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Login to GHCR Shelter
        uses: docker/login-action@v1
        with:
          registry: shelterdev.azurecr.io
          username: ${{ secrets.SHELTER_DEV_ACR_USERNAME }}
          password: ${{ secrets.SHELTER_DEV_ACR_PASSWORD }}
      #- name: Login to GHCR Prod
      #  uses: docker/login-action@v1
      #  with:
      #    registry: shelterdev.azurecr.io
      #    username: ${{ github.repository_owner }}
      #    password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-proxy
        uses: docker/metadata-action@v5.0.0
        with:
          images: |
            shelterdev.azurecr.io/kardex-proxy

      - name: Extract metadata (tags, labels) for Docker
        id: meta-sim
        uses: docker/metadata-action@v5.0.0
        with:
          images: |
            shelterdev.azurecr.io/kardex-sim


      - name: Build + Push Kardex Sim
        uses: docker/build-push-action@v2
        with:
          context: ./kardex-sim
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-sim.outputs.tags }}
          labels: ${{ steps.meta-sim.outputs.labels }}
      - name: Build + Push Kardex Proxy
        uses: docker/build-push-action@v2
        with:
          context: ./kardex-proxy
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-proxy.outputs.tags }}
          labels: ${{ steps.meta-proxy.outputs.labels }}

